# Generated by Django 2.2.6 on 2020-01-16 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='subcategory name', max_length=255, null=True)),
                ('monitor_name', models.CharField(blank=True, help_text='monitor name', max_length=255, null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('subscription_type', models.CharField(max_length=255)),
                ('condition', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, help_text='price per month', max_digits=10)),
                ('playbox_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('support_contract', models.DecimalField(decimal_places=2, max_digits=10)),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('extra_income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Category')),
            ],
        ),
    ]
