# Generated by Django 2.2.6 on 2020-01-16 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='start_date',
            field=models.DateField(),
        ),
    ]
