# Generated by Django 2.2.6 on 2020-01-30 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='email',
            field=models.EmailField(max_length=60, verbose_name='email'),
        ),
    ]
