# Generated by Django 2.2.6 on 2019-12-30 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='monitor_name',
            field=models.CharField(blank=True, help_text='monitor name', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(blank=True, help_text='subcategory name', max_length=255, null=True),
        ),
    ]
