# Generated by Django 2.2.6 on 2020-02-06 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='in_progress',
            field=models.BooleanField(default=True, help_text='licensed active'),
        ),
    ]
