# Generated by Django 2.2.6 on 2020-01-30 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20200130_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='email',
            field=models.EmailField(blank=True, max_length=60, null=True, verbose_name='email'),
        ),
    ]
