# Generated by Django 2.2.6 on 2020-01-30 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_auto_20200130_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='extra_income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='in_progress',
            field=models.BooleanField(blank=True, default=True, help_text='licensed active', null=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='playbox_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='price per month', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='subscription_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='support_contract',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
