# Generated by Django 2.2.6 on 2020-01-25 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FranchiseSummary',
            fields=[
            ],
            options={
                'verbose_name': 'franchise sales summary',
                'verbose_name_plural': 'franchise summary',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('customers.franchisecustomer',),
        ),
    ]
