# Generated by Django 2.2.6 on 2020-01-16 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20200116_2112'),
        ('customers', '0002_auto_20200116_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='franchisecustomer',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='category.Category'),
        ),
    ]
